### ISSUE TITLE
[question] Using msg.sender with Multicall

### ISSUE THREAD

**Issue by bonkrat** [EthWorks/useDApp#341]
First of all, just want to say thank your or your work on `useDapp`, it does not go unappreciated!

I’m wondering if there’s any guidance on using `msg.sender` with `useContractCall` along with the MultiCall contract. For instance, something like this pseudo code:

```solidity
function getEntries() public view returns uint256[] {
    entries[msg.sender]
}
```

Since there is a Multicall contract batching the calls the `msg.sender` will be that contract instead of the original address. Is there an intended way around this, or am I missing something? I’ve read that the OpenZeppelin version of the Multicall contract will delegate `msg.sender` so that it is the original initiator of the transaction, but I don’t think the MakerDAO version does. Any advice would be much appreciated!

**Comment by stalkeronlysolo** [comment]
did you find solution to this?

**Comment by bonkrat** [comment]
Not specifically, but I think I figured out that any public function that is not set as read only `view` will not use the multicall contract. The data in the getter functions I was using is all public anyway, so I changed my usage in my view methods from `msg.sender` to use an address parameter.  

Basically just use `msg.sender` when you are interacting with the contract and not just reading data.

**Comment by stalkeronlysolo** [comment]
I cant i have a withdraw method it has to use msg.sender, it is funny how it works in python and remix!

**Comment by bonkrat** [comment]
The other functions in my contract that used `msg.sender` worked fine for me as they didn’t use multicall. The only methods in my contract that used multicall were the view methods.

**Comment by damianlluch** [comment]
Hi, I am getting this error when connecting to Avalanche with useDapp.


My configuration is as follows:

```
const config: Config = {
    autoConnect: false,
    supportedChains: [
      ChainId.Mainnet,
      ChainId.Rinkeby,
      ChainId.BSC,
      ChainId.BSCTestnet,
      ChainId.Avalanche
    ],
  };
```
In the other networks I don't get any error.
I'm not sure what this multicall error is...

any suggestions?

thanks


```
index.js:1 Missing multicall address for chain id 43113 
    at ChainStateProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50332:5)
    at LocalMulticallProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49824:5)
    at BlockNumberProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50028:5)
    at Web3ReactProvider (http://localhost:3000/static/js/vendors~main.chunk.js:51790:27)
    at EthersProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49764:5)
    at DAppProviderWithConfig (http://localhost:3000/static/js/vendors~main.chunk.js:49717:5)
    at ConfigProvider (http://localhost:3000/static/js/vendors~main.chunk.js:50588:5)
    at DAppProvider (http://localhost:3000/static/js/vendors~main.chunk.js:49697:5)
    at r (http://localhost:3000/static/js/vendors~main.chunk.js:102624:19)
    at Providers (http://localhost:3000/static/js/main.chunk.js:208:5)
    at App
```

**Comment by bonkrat** [comment]
@damianlluch It looks like you need to set an address for a Multicall contract. I believe `useDapp` is supposed to deploy one for you locally. In one of my projects I deploy this contract locally as part of my hard hat deploy scripts, but it is up to you.  In other environments you can either deploy your own multi call contract or use one that is already deployed to that chain by specifying its address.

See https://github.com/makerdao/multicall for an explaination of Multicall contracts and info where to find them.
